name: CI
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (dummy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  test:
    name: Test (dummy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
