name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: cybozu/octoken-action@4a9fee096e6a1970d4cadfb08b231048ca851c85 # v1
        id: create-iat
        with:
          github_app_id: ${{ secrets.RELEASE_GITHUB_APP_ID}}
          github_app_private_key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # v3
        id: release
        with:
          command: manifest
          token: ${{ steps.create-iat.outputs.token }}
