name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: cybozu/octoken-action@v1
        id: create-iat
        with:
          github_app_id: ${{ secrets.RELEASE_GITHUB_APP_ID}}
          github_app_private_key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ steps.create-iat.outputs.token }}
