name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: create-iat
        with:
          app-id: ${{ secrets.RELEASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3
        id: release
        with:
          command: manifest
          token: ${{ steps.create-iat.outputs.token }}
