name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: cybozu/octoken-action@c72648d598d172cb5785587f6243bbd09774d034 # v1
        id: create-iat
        with:
          github_app_id: ${{ secrets.RELEASE_GITHUB_APP_ID}}
          github_app_private_key: ${{ secrets.RELEASE_GITHUB_APP_KEY }}
      - uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # v3
        id: release
        with:
          command: manifest
          token: ${{ steps.create-iat.outputs.token }}
